clusterGroup:
  name: hub
  isHubCluster: true

  namespaces:
    - vault
    - golang-external-secrets
    - mlops
    - openshift-storage
    - redhat-ods-operator
    - inferencing-app

  projects:
    - hub
    - mlops
    - openshift-storage
    - inferencing-app

  subscriptions:
    odf:
      name: odf-operator
      namespace: openshift-storage

    rhods:
      name: rhods-operator
      namespace: openshift-operators
      channel: stable

    crunchy:
      name: crunchy-postgres-operator
      source: certified-operators
      namespace: openshift-operators

    servicemesh:
      name: servicemeshoperator
      namespace: openshift-operators
      channel: stable

  applications:
    openshift-data-foundations:
      name: openshift-data-foundations
      namespace: openshift-storage
      project: mlops
      path: charts/all/openshift-data-foundations

    mlflow:
      name: mlflow-server
      namespace: mlops
      project: mlops
      path: charts/all/mlflow-server
      overrides:
      # - name: odhApplication.enabled
      #   value: true
      - name: objectStorage.objectBucketClaim.enabled
        value: true

    jobs:
      name: jobs
      namespace: default
      project: default
      path: charts/all/jobs

    # credit-fraud-model-app deployed using a local chart
    inferencing-app:
      name: inferencing-app
      namespace: inferencing-app
      project: inferencing-app
      path: charts/all/inferenceapp

    vault:
      name: vault
      namespace: vault
      project: hub
      chart: hashicorp-vault
      chartVersion: 0.1.*

    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: hub
      chart: golang-external-secrets
      chartVersion: 0.1.*
