# # Source: blank/templates/buildconfig.yaml
# apiVersion: build.openshift.io/v1
# kind: BuildConfig
# metadata:
#   name: exp
#   labels:
#     app: credit-fraud-detection-demo
#   namespace: credit-fraud-model
# spec:
#   source:
#     git:
#       uri: https://github.com/arslankhanali/credit-fraud-detection-demo
#     contextDir: application
#     type: Git
#   strategy:
#     type: Docker                      
#     dockerStrategy:
#       dockerfilePath: Dockerfile
#     #   from:
#     #     kind: ImageStreamTag       # Use an imagestream tag as 'FROM'. so instead of download image `again` it fetches from IS we created
#     #     namespace: credit-fraud-model    # Which project?
#     #     name: credit-fraud-detection-demo-is:latest         # Use the imagestream created above
#   output:
#     to:
#       kind: ImageStreamTag
#       name: credit-fraud-detection-demo-exp:latest  # Use the templated value
#   triggers:
#   - type: ImageChange