apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/hook: "PostSync"
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: image-registry.openshift-image-registry.svc:5000/{{ .Values.namespace }}/{{ .Values.appName }}-is-app:latest
        # image: {{ .Values.appName }}:latest
        env:
        - name: INFERENCE_ENDPOINT
          value: {{ .Values.inferenceEndpoint }}
        ports:
        - containerPort: {{ .Values.port }}
          name: http
          protocol: {{ .Values.protocol }}
