apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.appName }}-route
  labels:
    app: {{ .Values.appName }}
spec:
  port:
    targetPort: {{ .Values.port }}-tcp
  to:
    kind: Service
    name: {{ .Values.appName }}-svc
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
