apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-svc
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - name: {{ .Values.port }}-tcp
    port: {{ .Values.port }}
    protocol: {{ .Values.protocol }}
    targetPort: {{ .Values.port }}
  selector:
    app: {{ .Values.appName }}
  sessionAffinity: None
  type: ClusterIP
